# Nixpacks configuration for Discord bot with Python support
[phases.setup]
nixPkgs = [
  "nodejs_18",
  "npm",
  "python311",
  "python311Packages.pip",
  "python311Packages.pillow",
  "python311Packages.requests",
  "fontconfig",
  "dejavu_fonts"
]

[phases.install]
cmds = [
  "npm ci",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "npm start"
